Qt 6.7.3 source code

diff --git a/qtwebengine/src/3rdparty/chromium/third_party/vulkan-deps/spirv-tools/src/.github/workflows/autoroll.yml b/qtwebengine/src/3rdparty/chromium/third_party/vulkan-deps/spirv-tools/src/.github/workflows/autoroll.yml
--- a/qtwebengine/src/3rdparty/chromium/third_party/vulkan-deps/spirv-tools/src/.github/workflows/autoroll.yml
+++ b/qtwebengine/src/3rdparty/chromium/third_party/vulkan-deps/spirv-tools/src/.github/workflows/autoroll.yml
@@ -1,4 +1,6 @@
 name: Update dependencies
+permissions:
+  contents: read
 
 on:
   schedule:
@@ -7,6 +9,9 @@ on:
 
 jobs:
   update-dependencies:
+    permissions:
+      contents: write
+      pull-requests: write
     name: Update dependencies
     runs-on: ubuntu-latest
 
@@ -18,7 +23,7 @@ jobs:
         run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
 
       - name: Update PATH
-        run: echo "./depot_tools" >> $GITHUB_PATH
+        run: echo "$(pwd)/depot_tools" >> $GITHUB_PATH
 
       - name: Download dependencies
         run: python3 utils/git-sync-deps
@@ -38,11 +43,14 @@ jobs:
             echo "changed=true" >> $GITHUB_OUTPUT
           fi
         id: update_dependencies
-     
       - name: Push changes and create PR
         if: steps.update_dependencies.outputs.changed == 'true'
         run: |
           git push --force --set-upstream origin roll_deps
-          gh pr create --label 'kokoro:run' --base main -f -r s-perron
+          # Create a PR. If it aready exists, the command fails, so ignore the return code.
+          gh pr create --base main -f -r s-perron || true 
+          # Add the 'kokoro:run' label so that the kokoro tests will be run.
+          gh pr edit --add-label 'kokoro:run'
+          gh pr merge --auto --squash
         env:
           GITHUB_TOKEN: ${{ github.token }}
